# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [183]:
import numpy as np

2. Create a null vector of size 10 

In [184]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [185]:
newArr = np.arange(10,50)
newArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [186]:
newArr.shape

(40,)

5. Print the type of the previous array in question 3

In [187]:
newArr.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [188]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [189]:
newArr.ndim

1

8. Create a boolean array with all the True values

In [190]:
arr2 = np.ones(10,dtype="bool")
arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [191]:
twoDimArr = np.arange(9).reshape(3,3)
twoDimArr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Create a three dimensional array



In [192]:
threeDimArr = np.arange(64).reshape(4,2,8)
threeDimArr

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [193]:
arr4 = np.arange(10)
print("Original Array")
print(arr4)
print("Reversed Array")
print(arr4[::-1])

Original Array
[0 1 2 3 4 5 6 7 8 9]
Reversed Array
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [194]:
arr5 = np.zeros(10)
print("Null Vector: ",arr5)
arr5[4] = 1
print("Fifth Value of the vector is now 1: ",arr5)

Null Vector:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Fifth Value of the vector is now 1:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [195]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [196]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype("float64")

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [197]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [198]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [199]:
arr6 = np.arange(20)
arr6[1:10:2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [200]:
arr6[1::2]=-1
arr6

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [201]:
arr = np.arange(10)
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [202]:
import numpy as np
arr7 = np.ones(25).reshape(5,5)
print("Original Array")
print("**************")
print(arr7)
print("**************")
print("New Array")
print("**************")
arr7[1:4,1:4] = 0
print(arr7)

Original Array
**************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
**************
New Array
**************
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [203]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [204]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [205]:
arr8 = np.arange(9).reshape(3,3)
print(arr8)
print("*********")
print(arr8[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
*********
[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [206]:
arr9 = np.arange(9).reshape(3,3)
print(arr9)
print("*********")
print(arr9[1][1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
*********
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [207]:
arr10 = np.arange(9).reshape(3,3)
print(arr10)
print("*********")
print(arr10[0:2,2:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
*********
[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [208]:
from numpy import random
arr11 = random.randint(1000,size=100)
print(arr11.reshape(10,10))
print("")
print("Minimum Number is: ")
print(arr11.min())
print("Maximum Number is: ")
print(arr11.max())

[[726 443 389 159 756 833 457 948 965 621]
 [685 988 387  46 465 790 142 963  25 383]
 [381 283   2 350 475 492 504 372 673 269]
 [135 652 378   3 418 407 174 376 407 263]
 [199 894 804 320 887 832 191 729 294 422]
 [560 162 308 543 482 612 256 300 936 664]
 [177  91 931 916 379 182 823 917  65 779]
 [  4 749 964 907 557 815 312 987 251 506]
 [425 233 508 676 100 207 778 519 398 234]
 [601 462 351 626 656 902 675 828 852 980]]

Minimum Number is: 
2
Maximum Number is: 
988


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [209]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [210]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.searchsorted(a,np.intersect1d(a,b)))

[1 5]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [211]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names != 'Will']

array([[-0.98611162, -0.28474517,  0.74845514, -0.8297581 ],
       [-0.25716147,  1.30509464,  0.27736041,  0.117381  ],
       [ 1.57485309, -0.21643143,  0.41732887,  1.03601735],
       [ 0.97992638, -2.01891554, -0.75188256,  0.82593321],
       [ 0.62379562,  0.7066468 ,  0.19444777,  1.49135411]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [212]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask = (names != "Will") & (names != 'Joe')
data[mask]

array([[ 1.25851492,  0.01964931, -0.4149026 ,  0.12287271],
       [ 0.77243523, -1.69089769,  0.43129816, -0.09535294]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [213]:
arr12 = np.arange(1.0,16).reshape(5,3)
arr12

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [214]:
arr13 = np.arange(1.0,17).reshape(2,2,4)
arr13

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [215]:
np.swapaxes(arr13,2,0)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [216]:
from numpy import random
arr14 = np.array(random.rand(10))
print(arr14)
print("*****************")
arr15 = np.sqrt(arr14)
print(arr15)
print("*****************")
np.where(arr15 < 0.5,0,arr15)


[0.85455704 0.86760316 0.09232587 0.17414909 0.63573828 0.36310674
 0.3902153  0.26373204 0.63915276 0.93574771]
*****************
[0.92442254 0.93145218 0.30385173 0.41731175 0.79733198 0.60258339
 0.62467215 0.51354848 0.7994703  0.96734053]
*****************


array([0.92442254, 0.93145218, 0.        , 0.        , 0.79733198,
       0.60258339, 0.62467215, 0.51354848, 0.7994703 , 0.96734053])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [217]:
arr16 = np.random.randint(1,100,12)
print(arr16)
print("------------------------------------")
arr17 = np.random.randint(1,100,12)
print(arr17)
print("------------------------------------")
arr18 = np.array(np.maximum(arr16,arr17))
print(arr18)

[ 4  6 79  2 41 92 87 13 76 14 50 12]
------------------------------------
[26 23 66 57 43  3  7 33 49 55 59  7]
------------------------------------
[26 23 79 57 43 92 87 33 76 55 59 12]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [218]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
arr19 = np.unique(np.sort(names))
print(arr19)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [219]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
arr20 = np.setdiff1d(a,b)
print(arr20)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [220]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
arr21 = np.delete(sampleArray,1,axis=1)
arr22 = np.insert(arr21,1,newColumn,axis=1)
print(arr22)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [221]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [222]:
print("Random Array:")
arr23 = np.random.randint(1,100,size=20)
print(arr23)
arr24 = np.cumsum(arr23)
print("Array After Cumulative Sum:")
print(arr24)

Random Array:
[14 59 83 29 30 52 78 29 40 38 44 37 60 93 22 67 39 63 25 74]
Array After Cumulative Sum:
[ 14  73 156 185 215 267 345 374 414 452 496 533 593 686 708 775 814 877
 902 976]
